spring:
  application:
    name: bankapp

  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG